#**Numpy Tutorial**

In [2]:
import numpy as np

In [3]:
myarr=np.array([[1,2,3,4,5]],np.int8)

In [4]:
myarr

array([[1, 2, 3, 4, 5]], dtype=int8)

In [5]:
myarr[0]

array([1, 2, 3, 4, 5], dtype=int8)

In [6]:
myarr.shape

(1, 5)

**Array Creation**


In [7]:
np.array({32,33,38})

array({32, 33, 38}, dtype=object)

In [8]:
zeros=np.zeros((2,5))

In [9]:
zeros.dtype

dtype('float64')

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arng=np.arange(15)

In [12]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace=np.linspace(1,5,5)   #linspace(start,end,no.of elements)

In [14]:
lspace

array([1., 2., 3., 4., 5.])

In [15]:
emp=np.empty((2,5))
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
emp_like=np.empty_like(lspace)

In [17]:
emp_like

array([1., 2., 3., 4., 5.])

In [18]:
arg=np.arange(99)
arg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
arr=arg.reshape(3,33)


In [20]:
arr=arr.ravel()

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
matrix.sum(axis=0)

array([ 9, 12, 15])

In [26]:
matrix.sum(axis=1)

array([ 3, 12, 21])

In [27]:
matrix.T  #Transpose matrix

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [28]:
matrix.flat

In [35]:
for i in matrix.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [36]:
matrix.ndim

2

In [38]:
matrix.nbytes

72

In [42]:
one=np.array([1,2,3,34,5])

In [43]:
one.argmax()

np.int64(3)

In [44]:
one.argmin()

np.int64(0)

In [45]:
one.argsort()  #give ascenorder index not vlaue 

array([0, 1, 2, 4, 3])

In [46]:
arrr = np.arange(9).reshape(3, 3)
arrr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arrr.argmax(axis=0)

array([2, 2, 2])

In [48]:
arrr.argmax()


np.int64(8)

In [49]:
arr.argmin()

np.int64(0)

In [51]:
arrr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [52]:
arrr*matrix

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [53]:
arrr+matrix

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [54]:
np.sqrt(arrr*matrix)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [58]:
arrr.sum()

np.int64(36)

In [59]:
arrr.max()


np.int64(8)

In [62]:
np.where(arrr>6)

(array([2, 2]), array([1, 2]))

In [63]:
np.count_nonzero(arrr)

8

In [64]:
py_ar=[0,8,6,5]

In [65]:
np_ar=np.array(py_ar)

In [66]:
sys.getsizeof(1)*len(py_ar)

112

In [69]:
np_ar.itemsize*np_ar.size

32

In [71]:
np_ar.tolist()

[0, 8, 6, 5]